### PR TITLE
Try to really guess the userAgentLocale when general.useragent.locale…

### LINKED ISSUE #69: removeDefaultBookmarks seems not to work anymore on FF57
It seems like removeDefaultBookmarks is not working for FF57 anymore. 
It leaves "Getting Started" in the bookmarks toolbar.
Same cck2.cfg worked fine in FF56 and before.

### PR DESCRIPTION
**Pull request by shadeslayer**
… fails

Fixes #69

### CODE REVIEW

**Comment by mkaply** [comment]
Was this on 58 or 59?

**Comment by mkaply** [comment]
So I think the right API here is actually  Services.locale.getRequestedLocale()

This pref was removed in 59.

**Comment by shadeslayer** [comment]
This was on Firefox 58

**Comment by shadeslayer** [comment]
Using Services.locale.getRequestedLocale caused a segfault on Firefox 58 for me.

It also seems this entire code path is really slow on ARM since the rest of the UI get's setup and the bookmarks appear after 10-15 seconds.

**Comment by mkaply** [comment]
OK, I'm really confused. Firefox 58 still had the general.useragent.locale preference.

Are you on Linux?

**Comment by shadeslayer** [comment]
I am indeed on Linux. While FF 58 still has general.useragent.locale, the value that I get from Preferences.defaults.get is undefined. In about:config, the same value is set to en when in reality the locale should have been de.

**Comment by shadeslayer** [comment]
Bump?

**Comment by mkaply** [comment]
Sorry. I still don't understand your last few comments. 

Can you tell me the value of intl.locale.matchOS on your Firefox 58?

**Comment by shadeslayer** [comment]
It's set to false for some reason :S

**Comment by mkaply** [comment]
Most Linux versions set it to true. Strange. I think I know of a better way to do this because I actually need to get the chrome locale. I'll try another patch.

**Comment by shadeslayer** [comment]
Yeah, it's quite odd

**Comment by mkaply** [comment]
I ended up with a different patch for this for Firefox 60. Please take a look. Thanks!

**Pull request closed without merging**
