### PR TITLE
Add new code for hiding devtools

### PR DESCRIPTION
**Pull request by mkaply**

### CODE REVIEW

**Comment by kaihendry** [comment]
I attempted to grab the relevant bits and integrate it **but F12 still seems to work**: https://github.com/Webconverger/webconverger-addon/commit/f390dc402c74d6019141da936f0fc280361357dd

Tbh I have no idea how to debug if the code is even running.

**Comment by mkaply** [comment]
That's odd. in my testing, It removed F12 as well. Best way to debug is to throw in some "Components.utils.reportError('foo')" and use the Javascript console. I'll see what I can figure out.

**Comment by kaihendry** [comment]
Wonder if the old `let console = (Cu.import("resource://gre/modules/devtools/Console.jsm", {})).console` trick works still? Still by development iteration is maddening ...  https://www.youtube.com/watch?v=aBIqpEFmfUI

**Comment by kaihendry** [comment]
Oh btw, here is your work in https://github.com/Webconverger/webconverger-addon/commit/cbad324af0ddeee25ae23b725ea3f71f817b6c71

**Comment by mkaply** [comment]
No, your console trick won't work. The devtools JS console is completely different on Firefox 52. And yes, I agree it's maddening.

**Pull request merged**
